# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/sumarea_fifo/sumarea_fifo.xci
# IP: The module: 'sumarea_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/sumarea_fifo/sumarea_fifo/sumarea_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sumarea_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/sumarea_fifo/sumarea_fifo/sumarea_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'sumarea_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/sumarea_fifo/sumarea_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sumarea_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/sumarea_fifo/sumarea_fifo.xci
# IP: The module: 'sumarea_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/sumarea_fifo/sumarea_fifo/sumarea_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sumarea_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/sumarea_fifo/sumarea_fifo/sumarea_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'sumarea_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/sumarea_fifo/sumarea_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sumarea_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
