# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/tmnguyen/mu2e_monitor_firmware_original/firmware_original/mu2e_1.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fc5c_rst_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/tmnguyen/mu2e_monitor_firmware_original/firmware_original/mu2e_1.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fc5c_rst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/tmnguyen/mu2e_monitor_firmware_original/firmware_original/mu2e_1.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fc5c_rst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/tmnguyen/mu2e_monitor_firmware_original/firmware_original/mu2e_1.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fc5c_rst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/tmnguyen/mu2e_monitor_firmware_original/firmware_original/mu2e_1.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fc5c_rst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/tmnguyen/mu2e_monitor_firmware_original/firmware_original/mu2e_1.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_rst_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fc5c_rst_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
