#
# Vivado (TM) v2016.2 (64-bit)
#
# recreate_project.tcl: Tcl script for re-creating project 'mu2e_1'
#
# Generated by Vivado on Fri Jan 25 13:50:12 EST 2019
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (recreate_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/add8.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/iobus.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/lfsr_n.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/crc32.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/cksum.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ipbuf.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fmc164_readout_buffer.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fmc164.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/gbe.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/tclkb_driver.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/tclka_receiver.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/tclka_counter.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/i2c.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/clkfreq.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/amc502.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/sendpkt.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ip.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/arprep.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/txether.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/icmp.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/streampkt.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/udp.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ipheader.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/icmprep.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/udpbuffer.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/arp.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/gbe_stream_buffer.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/txbuffer.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/arpreq.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ethernet.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/arptab.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fmc164_threshold_trigger.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fmc164_interface.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/amc502_interface.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/iobus_interface.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/gbe_interface.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/top_amc502_fmc164.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_parse_new.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_match.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_lv1count.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_pixel_fifo.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4rx.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/crc32x64.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_udpbuffer.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_udp.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_txbuffer.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_sendpkt.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_icmpreq.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_icmprep.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_icmp.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_ethernet.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_arpreq.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_arprep.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_arp.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_arbiter.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_readout.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_pulser.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_event_builder.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_bcocounter.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4tx.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_interface.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_interface.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/top_amc502_fei4_xaui.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fmc164_adc_buffer.vhd"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.srcs/sources_1/adc_pulse_height.vhd"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.srcs/sources_1/adc_histogram.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/adc_fifo.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/top_amc502_xaui.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/top_amc502.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/top_null.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.sdk/monitor_null/Debug/monitor_null.elf"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.sdk/monitor_amc502/Debug/monitor_amc502_xaui.elf"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_trigger.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_readout_buffer.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_stream.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fei4_fifo.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/decoder_10b8b_rom.coe"
#    "/home/mjones/cae/hdl/project_3/project_3.srcs/sources_1/new/decoder_10b8b_rom.coe"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.sdk/monitor_amc502/Debug/monitor_amc502_xaui_fei4.elf"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.sdk/monitor_amc502/Debug/monitor_amc502_fmc164.elf"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/top_amc502_fmc228.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fmc228.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/fmc228_interface.vhd"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.srcs/sources_1/adc_trigger.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/hmc_spi.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/adc_buffer_streamer.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/adc_spi.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/adc_buffer_pool.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/lmk_spi.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/adc_buffer.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/jesd204_adc.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ilas.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/lfsr.vhd"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.sdk/monitor_amc502/Debug/monitor_amc502_fmc228.elf"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/latch_generator.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/event_generator.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_stream_buffer.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_streampkt.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/crc32x64rom.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/crc8x32_const.vhd"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.srcs/sources_1/crc8x32_lookup.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/validation.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/trigger.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/trigger_ram.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/xaui_trigger.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/top_fmc228_pcie.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/i2c_slave.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/trigger_in.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/system_trigger.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/link_interface.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/link.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/trigger_pipeline.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.sdk/monitor_amc502/Debug/monitor_fmc228_pcie.elf"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ip/xaui_0/xaui_0.xci"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ip/decoder_10b8b_rom/decoder_10b8b_rom.xci"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ip/fei4_pixel_fifo/fei4_pixel_fifo.xci"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ip/fei4_spy_fifo/fei4_spy_fifo.xci"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.srcs/sources_1/ip/jesd204_phy_0/jesd204_phy_0.xci"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xci"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_amc502.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_amc502.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/timing_null.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_amc502.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/timing_amc502.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_amc502.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_xaui.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/timing_amc502_xaui.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_amc502.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_xaui.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_fei4_fmc0.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/timing_amc502_fei4_xaui.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_amc502.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_fmc164.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/timing_amc502_fmc164.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_amc502.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_xaui.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_fmc228_fmc1.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/timing_amc502_fmc228.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_amc502.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/pins_fmc228_fmc1.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/constrs_1/timing_fmc228_pcie.xdc"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sim_1/sim_xaui_tb.vhd"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.srcs/sim_1/sim_xaui_tb_behav.wcfg"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sim_1/sim_streampkt_buffer_tb.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sim_1/sim_crc_tb.vhd"
#    "/home/mjones/cae/hdl/mu2e/firmware/mu2e_1.srcs/sim_1/sim_trigger_tb.vhd"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.srcs/sim_1/trigger_in_tb.vhd"
#    "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.srcs/sim_1/system_trigger_tb.vhd"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "recreate_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
#create_project mu2e_1 ./mu2e_1 -part xc7k420tffg1156-2
create_project -force mu2e_1 ./mu2e_1 -part xc7k420tffg1156-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
set_msg_config  -ruleid {1}  -id {[BD 41-1306]}  -suppress  -source 2
set_msg_config  -ruleid {2}  -id {[BD 41-1271]}  -suppress  -source 2


# Set project properties
set obj [get_projects mu2e_1]
set_property "default_lib" "xil_defaultlib" $obj
set_property "generate_ip_upgrade_log" "0" $obj
set_property "part" "xc7k420tffg1156-2" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "source_mgmt_mode" "None" $obj
set_property "target_language" "VHDL" $obj
set_property "xpm_libraries" "XPM_MEMORY" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/add8.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/iobus.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/lfsr_n.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/crc32.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/cksum.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ipbuf.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fmc164_readout_buffer.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fmc164.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/gbe.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/tclkb_driver.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/tclka_receiver.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/tclka_counter.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/i2c.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/clkfreq.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/amc502.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/sendpkt.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ip.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/arprep.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/txether.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/icmp.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/streampkt.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/udp.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ipheader.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/icmprep.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/udpbuffer.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/arp.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/gbe_stream_buffer.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/txbuffer.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/arpreq.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ethernet.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/arptab.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fmc164_threshold_trigger.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fmc164_interface.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/amc502_interface.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/iobus_interface.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/gbe_interface.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/top_amc502_fmc164.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_parse_new.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_match.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_lv1count.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_pixel_fifo.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4rx.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/crc32x64.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_udpbuffer.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_udp.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_txbuffer.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_sendpkt.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_icmpreq.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_icmprep.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_icmp.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_ethernet.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_arpreq.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_arprep.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_arp.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_arbiter.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_readout.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_pulser.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_event_builder.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_bcocounter.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4tx.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_interface.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_interface.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/top_amc502_fei4_xaui.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fmc164_adc_buffer.vhd"]"\
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.srcs/sources_1/adc_pulse_height.vhd"]"\
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.srcs/sources_1/adc_histogram.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/adc_fifo.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/top_amc502_xaui.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/top_amc502.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/top_null.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.sdk/monitor_null/Debug/monitor_null.elf"]"\
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.sdk/monitor_amc502/Debug/monitor_amc502_xaui.elf"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_trigger.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_readout_buffer.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_stream.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fei4_fifo.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/decoder_10b8b_rom.coe"]"\
 "[file normalize "$origin_dir/../../project_3/project_3.srcs/sources_1/new/decoder_10b8b_rom.coe"]"\
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.sdk/monitor_amc502/Debug/monitor_amc502_xaui_fei4.elf"]"\
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.sdk/monitor_amc502/Debug/monitor_amc502_fmc164.elf"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/top_amc502_fmc228.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fmc228.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/fmc228_interface.vhd"]"\
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.srcs/sources_1/adc_trigger.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/hmc_spi.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/adc_buffer_streamer.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/adc_spi.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/adc_buffer_pool.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/lmk_spi.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/adc_buffer.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/jesd204_adc.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ilas.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/lfsr.vhd"]"\
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.sdk/monitor_amc502/Debug/monitor_amc502_fmc228.elf"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/latch_generator.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/event_generator.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_stream_buffer.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_streampkt.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/crc32x64rom.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/crc8x32_const.vhd"]"\
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.srcs/sources_1/crc8x32_lookup.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/validation.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/trigger.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/trigger_ram.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/xaui_trigger.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/top_fmc228_pcie.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/i2c_slave.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/trigger_in.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/system_trigger.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/link_interface.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/link.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/trigger_pipeline.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.sdk/monitor_amc502/Debug/monitor_fmc228_pcie.elf"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "sources_1/add8.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/iobus.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/lfsr_n.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/crc32.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/cksum.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/ipbuf.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fmc164_readout_buffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fmc164.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/gbe.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/tclkb_driver.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/tclka_receiver.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/tclka_counter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/i2c.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/clkfreq.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/amc502.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/sendpkt.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/ip.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/arprep.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/txether.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/icmp.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/streampkt.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/udp.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/ipheader.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/icmprep.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/udpbuffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/arp.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/gbe_stream_buffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/txbuffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/arpreq.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/ethernet.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/arptab.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fmc164_threshold_trigger.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fmc164_interface.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/amc502_interface.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/iobus_interface.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/gbe_interface.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/top_amc502_fmc164.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "synthesis" $file_obj
set_property "used_in_simulation" "0" $file_obj

set file "sources_1/fei4_parse_new.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4_match.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4_lv1count.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4_pixel_fifo.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4rx.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/crc32x64.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_udpbuffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_udp.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_txbuffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_sendpkt.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_icmpreq.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_icmprep.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_icmp.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_ethernet.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_arpreq.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_arprep.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_arp.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_arbiter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4_readout.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4_pulser.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4_event_builder.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4_bcocounter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4tx.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_interface.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4_interface.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/top_amc502_fei4_xaui.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "synthesis" $file_obj
set_property "used_in_simulation" "0" $file_obj

set file "sources_1/fmc164_adc_buffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/adc_pulse_height.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/adc_histogram.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/adc_fifo.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/top_amc502_xaui.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "synthesis" $file_obj
set_property "used_in_simulation" "0" $file_obj

set file "sources_1/top_amc502.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "synthesis" $file_obj
set_property "used_in_simulation" "0" $file_obj

set file "sources_1/top_null.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "synthesis" $file_obj
set_property "used_in_simulation" "0" $file_obj

set file "Debug/monitor_null.elf"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "implementation" $file_obj
set_property "used_in_simulation" "0" $file_obj

set file "Debug/monitor_amc502_xaui.elf"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "implementation" $file_obj
set_property "used_in_simulation" "0" $file_obj

set file "sources_1/fei4_trigger.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4_readout_buffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4_stream.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fei4_fifo.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "Debug/monitor_amc502_xaui_fei4.elf"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "implementation" $file_obj
set_property "used_in_simulation" "0" $file_obj

set file "Debug/monitor_amc502_fmc164.elf"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "implementation" $file_obj
set_property "used_in_simulation" "0" $file_obj

set file "sources_1/top_amc502_fmc228.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "synthesis" $file_obj
set_property "used_in_simulation" "0" $file_obj

set file "sources_1/fmc228.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/fmc228_interface.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/adc_trigger.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/hmc_spi.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/adc_buffer_streamer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/adc_spi.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/adc_buffer_pool.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/lmk_spi.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/adc_buffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/jesd204_adc.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/ilas.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/lfsr.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "Debug/monitor_amc502_fmc228.elf"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "implementation" $file_obj
set_property "used_in_simulation" "0" $file_obj

set file "sources_1/latch_generator.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/event_generator.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_stream_buffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_streampkt.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/crc32x64rom.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/crc8x32_const.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/crc8x32_lookup.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/validation.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/trigger.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/trigger_ram.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/xaui_trigger.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/top_fmc228_pcie.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources_1/i2c_slave.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/trigger_in.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/system_trigger.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/link_interface.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/link.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "sources_1/trigger_pipeline.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "hep337dev" $file_obj

set file "Debug/monitor_fmc228_pcie.elf"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "scoped_to_cells" "U0/microblaze_I" $file_obj
set_property "scoped_to_ref" "microblaze_mcs_0" $file_obj
set_property "used_in" "implementation" $file_obj
set_property "used_in_simulation" "0" $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "top_fmc228_pcie" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ip/xaui_0/xaui_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ip/decoder_10b8b_rom/decoder_10b8b_rom.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ip/fei4_pixel_fifo/fei4_pixel_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ip/fei4_spy_fifo/fei4_spy_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.srcs/sources_1/ip/jesd204_phy_0/jesd204_phy_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/mu2e_1.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_amc502.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_amc502.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'constrs_null' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_null] ""]} {
  create_fileset -constrset constrs_null
}

# Set 'constrs_null' fileset object
set obj [get_filesets constrs_null]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_amc502.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_amc502.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_null] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_null.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/timing_null.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_null] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_null' fileset properties
set obj [get_filesets constrs_null]

# Create 'constrs_amc502' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_amc502] ""]} {
  create_fileset -constrset constrs_amc502
}

# Set 'constrs_amc502' fileset object
set obj [get_filesets constrs_amc502]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_amc502.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_amc502.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_amc502.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/timing_amc502.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_amc502' fileset properties
set obj [get_filesets constrs_amc502]
set_property "target_constrs_file" "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_amc502.xdc"]" $obj

# Create 'constrs_amc502_xaui' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_amc502_xaui] ""]} {
  create_fileset -constrset constrs_amc502_xaui
}

# Set 'constrs_amc502_xaui' fileset object
set obj [get_filesets constrs_amc502_xaui]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_amc502.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_amc502.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_xaui] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_xaui.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_xaui.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_xaui] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_amc502_xaui.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/timing_amc502_xaui.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_xaui] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_amc502_xaui' fileset properties
set obj [get_filesets constrs_amc502_xaui]
set_property "target_constrs_file" "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_amc502_xaui.xdc"]" $obj

# Create 'constrs_amc502_fei4_xaui' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_amc502_fei4_xaui] ""]} {
  create_fileset -constrset constrs_amc502_fei4_xaui
}

# Set 'constrs_amc502_fei4_xaui' fileset object
set obj [get_filesets constrs_amc502_fei4_xaui]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_amc502.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_amc502.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_fei4_xaui] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_xaui.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_xaui.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_fei4_xaui] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_fei4_fmc0.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_fei4_fmc0.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_fei4_xaui] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_amc502_fei4_xaui.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/timing_amc502_fei4_xaui.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_fei4_xaui] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_amc502_fei4_xaui' fileset properties
set obj [get_filesets constrs_amc502_fei4_xaui]
set_property "target_constrs_file" "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_amc502_fei4_xaui.xdc"]" $obj

# Create 'constrs_amc502_fmc164' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_amc502_fmc164] ""]} {
  create_fileset -constrset constrs_amc502_fmc164
}

# Set 'constrs_amc502_fmc164' fileset object
set obj [get_filesets constrs_amc502_fmc164]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_amc502.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_amc502.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_fmc164] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_fmc164.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_fmc164.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_fmc164] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_amc502_fmc164.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/timing_amc502_fmc164.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_fmc164] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_amc502_fmc164' fileset properties
set obj [get_filesets constrs_amc502_fmc164]
set_property "target_constrs_file" "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_amc502_fmc164.xdc"]" $obj

# Create 'constrs_amc502_fmc228' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_amc502_fmc228] ""]} {
  create_fileset -constrset constrs_amc502_fmc228
}

# Set 'constrs_amc502_fmc228' fileset object
set obj [get_filesets constrs_amc502_fmc228]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_amc502.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_amc502.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_fmc228] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_xaui.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_xaui.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_fmc228] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_fmc228_fmc1.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_fmc228_fmc1.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_fmc228] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_amc502_fmc228.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/timing_amc502_fmc228.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_amc502_fmc228] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_amc502_fmc228' fileset properties
set obj [get_filesets constrs_amc502_fmc228]
set_property "target_constrs_file" "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_amc502_fmc228.xdc"]" $obj

# Create 'constrs_fmc228_pcie' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_fmc228_pcie] ""]} {
  create_fileset -constrset constrs_fmc228_pcie
}

# Set 'constrs_fmc228_pcie' fileset object
set obj [get_filesets constrs_fmc228_pcie]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_amc502.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_amc502.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_fmc228_pcie] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/pins_fmc228_fmc1.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/pins_fmc228_fmc1.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_fmc228_pcie] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_fmc228_pcie.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "constrs_1/timing_fmc228_pcie.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_fmc228_pcie] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_fmc228_pcie' fileset properties
set obj [get_filesets constrs_fmc228_pcie]
set_property "target_constrs_file" "[file normalize "$origin_dir/mu2e_1.srcs/constrs_1/timing_fmc228_pcie.xdc"]" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/mu2e_1.srcs/sim_1/sim_xaui_tb.vhd"]"\
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.srcs/sim_1/sim_xaui_tb_behav.wcfg"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sim_1/sim_streampkt_buffer_tb.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sim_1/sim_crc_tb.vhd"]"\
 "[file normalize "$origin_dir/mu2e_1.srcs/sim_1/sim_trigger_tb.vhd"]"\
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.srcs/sim_1/trigger_in_tb.vhd"]"\
 "[file normalize "$origin_dir/../../mu2e_1/firmware/mu2e_1.srcs/sim_1/system_trigger_tb.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
set file "sim_1/sim_xaui_tb.vhd"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sim_1/sim_streampkt_buffer_tb.vhd"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "simulation" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "sim_1/sim_crc_tb.vhd"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "simulation" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "sim_1/sim_trigger_tb.vhd"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "simulation" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "sim_1/trigger_in_tb.vhd"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "simulation" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "sim_1/system_trigger_tb.vhd"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "system_trigger_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj
set_property "xsim.view" "/home/mjones/cae/hdl/mu2e_1/firmware/mu2e_1.srcs/sim_1/sim_xaui_tb_behav.wcfg" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k420tffg1156-2 -flow {Vivado Synthesis 2016} -strategy "Flow_PerfOptimized_high" -constrset constrs_fmc228_pcie
} else {
  set_property strategy "Flow_PerfOptimized_high" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "constrset" "constrs_fmc228_pcie" $obj
set_property "needs_refresh" "1" $obj
set_property "part" "xc7k420tffg1156-2" $obj
set_property "steps.synth_design.args.fanout_limit" "400" $obj
set_property "steps.synth_design.args.fsm_extraction" "one_hot" $obj
set_property "steps.synth_design.args.keep_equivalent_registers" "1" $obj
set_property "steps.synth_design.args.resource_sharing" "off" $obj
set_property "steps.synth_design.args.no_lc" "1" $obj
set_property "steps.synth_design.args.shreg_min_size" "5" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k420tffg1156-2 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_fmc228_pcie -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "constrset" "constrs_fmc228_pcie" $obj
set_property "part" "xc7k420tffg1156-2" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:mu2e_1"
