#
#  This describes the pins on an FMC164 card installed
#  on the AMC502 in the upper FMC slot (FMC0).  This is
#  the DDR interface.
#

set_property PACKAGE_PIN R26 [get_ports che_clk_p]
set_property PACKAGE_PIN R27 [get_ports che_clk_n]
set_property PACKAGE_PIN L34 [get_ports cha_clk_p]
set_property PACKAGE_PIN K34 [get_ports cha_clk_n]

set_property PACKAGE_PIN G31 [get_ports {cha_data_p[0]}]
set_property PACKAGE_PIN F31 [get_ports {cha_data_n[0]}]
set_property PACKAGE_PIN E19 [get_ports {cha_data_p[1]}]
set_property PACKAGE_PIN D19 [get_ports {cha_data_n[1]}]
set_property PACKAGE_PIN K28 [get_ports {cha_data_p[2]}]
set_property PACKAGE_PIN K29 [get_ports {cha_data_n[2]}]
set_property PACKAGE_PIN E21 [get_ports {cha_data_p[3]}]
set_property PACKAGE_PIN E22 [get_ports {cha_data_n[3]}]
set_property PACKAGE_PIN J24 [get_ports {cha_data_p[4]}]
set_property PACKAGE_PIN J25 [get_ports {cha_data_n[4]}]
set_property PACKAGE_PIN M26 [get_ports {cha_data_p[5]}]
set_property PACKAGE_PIN M27 [get_ports {cha_data_n[5]}]
set_property PACKAGE_PIN E31 [get_ports {cha_data_p[6]}]
set_property PACKAGE_PIN D31 [get_ports {cha_data_n[6]}]
set_property PACKAGE_PIN H33 [get_ports {cha_data_p[7]}]
set_property PACKAGE_PIN G33 [get_ports {cha_data_n[7]}]

set_property PACKAGE_PIN K32 [get_ports {chc_data_p[0]}]
set_property PACKAGE_PIN J32 [get_ports {chc_data_n[0]}]
set_property PACKAGE_PIN L28 [get_ports {chc_data_p[1]}]
set_property PACKAGE_PIN L29 [get_ports {chc_data_n[1]}]
set_property PACKAGE_PIN K26 [get_ports {chc_data_p[2]}]
set_property PACKAGE_PIN K27 [get_ports {chc_data_n[2]}]
set_property PACKAGE_PIN F34 [get_ports {chc_data_p[3]}]
set_property PACKAGE_PIN E34 [get_ports {chc_data_n[3]}]
set_property PACKAGE_PIN H28 [get_ports {chc_data_p[4]}]
set_property PACKAGE_PIN G28 [get_ports {chc_data_n[4]}]
set_property PACKAGE_PIN L24 [get_ports {chc_data_p[5]}]
set_property PACKAGE_PIN K24 [get_ports {chc_data_n[5]}]
set_property PACKAGE_PIN J34 [get_ports {chc_data_p[6]}]
set_property PACKAGE_PIN H34 [get_ports {chc_data_n[6]}]
set_property PACKAGE_PIN H32 [get_ports {chc_data_p[7]}]
set_property PACKAGE_PIN G32 [get_ports {chc_data_n[7]}]

set_property PACKAGE_PIN B30 [get_ports {che_data_p[0]}]
set_property PACKAGE_PIN A31 [get_ports {che_data_n[0]}]
set_property PACKAGE_PIN D24 [get_ports {che_data_p[1]}]
set_property PACKAGE_PIN D25 [get_ports {che_data_n[1]}]
set_property PACKAGE_PIN C23 [get_ports {che_data_p[2]}]
set_property PACKAGE_PIN B23 [get_ports {che_data_n[2]}]
set_property PACKAGE_PIN E26 [get_ports {che_data_p[3]}]
set_property PACKAGE_PIN E27 [get_ports {che_data_n[3]}]
set_property PACKAGE_PIN F24 [get_ports {che_data_p[4]}]
set_property PACKAGE_PIN E24 [get_ports {che_data_n[4]}]
set_property PACKAGE_PIN H27 [get_ports {che_data_p[5]}]
set_property PACKAGE_PIN G27 [get_ports {che_data_n[5]}]
set_property PACKAGE_PIN G30 [get_ports {che_data_p[6]}]
set_property PACKAGE_PIN F30 [get_ports {che_data_n[6]}]
set_property PACKAGE_PIN F29 [get_ports {che_data_p[7]}]
set_property PACKAGE_PIN E29 [get_ports {che_data_n[7]}]

set_property PACKAGE_PIN D29 [get_ports {chg_data_p[0]}]
set_property PACKAGE_PIN D30 [get_ports {chg_data_n[0]}]
set_property PACKAGE_PIN G22 [get_ports {chg_data_p[1]}]
set_property PACKAGE_PIN G23 [get_ports {chg_data_n[1]}]
set_property PACKAGE_PIN B22 [get_ports {chg_data_p[2]}]
set_property PACKAGE_PIN A23 [get_ports {chg_data_n[2]}]
set_property PACKAGE_PIN A29 [get_ports {chg_data_p[3]}]
set_property PACKAGE_PIN A30 [get_ports {chg_data_n[3]}]
set_property PACKAGE_PIN A19 [get_ports {chg_data_p[4]}]
set_property PACKAGE_PIN A20 [get_ports {chg_data_n[4]}]
set_property PACKAGE_PIN B21 [get_ports {chg_data_p[5]}]
set_property PACKAGE_PIN A21 [get_ports {chg_data_n[5]}]
set_property PACKAGE_PIN C24 [get_ports {chg_data_p[6]}]
set_property PACKAGE_PIN C25 [get_ports {chg_data_n[6]}]
set_property PACKAGE_PIN A24 [get_ports {chg_data_p[7]}]
set_property PACKAGE_PIN A25 [get_ports {chg_data_n[7]}]



