# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ericp/Xilinx/mu2e_monitor_firmware_original/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/fei4_pixel_fifo/fei4_pixel_fifo.xci
# IP: The module: 'fei4_pixel_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ericp/Xilinx/mu2e_monitor_firmware_original/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/fei4_pixel_fifo/fei4_pixel_fifo/fei4_pixel_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fei4_pixel_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ericp/Xilinx/mu2e_monitor_firmware_original/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/fei4_pixel_fifo/fei4_pixel_fifo/fei4_pixel_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fei4_pixel_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ericp/Xilinx/mu2e_monitor_firmware_original/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/fei4_pixel_fifo/fei4_pixel_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fei4_pixel_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/ericp/Xilinx/mu2e_monitor_firmware_original/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/fei4_pixel_fifo/fei4_pixel_fifo.xci
# IP: The module: 'fei4_pixel_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ericp/Xilinx/mu2e_monitor_firmware_original/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/fei4_pixel_fifo/fei4_pixel_fifo/fei4_pixel_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fei4_pixel_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ericp/Xilinx/mu2e_monitor_firmware_original/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/fei4_pixel_fifo/fei4_pixel_fifo/fei4_pixel_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fei4_pixel_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ericp/Xilinx/mu2e_monitor_firmware_original/mu2e_monitor_firmware_original/firmware_New_v2/mu2e_1.srcs/sources_1/ip/fei4_pixel_fifo/fei4_pixel_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fei4_pixel_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
