# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/jesd204_phy_1.xci
# IP: The module: 'jesd204_phy_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/ip_0/jesd204_phy_1_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_phy_1_gt || ORIG_REF_NAME==jesd204_phy_1_gt}]

# XDC: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/ip_0/jesd204_phy_1_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_phy_1_gt || ORIG_REF_NAME==jesd204_phy_1_gt}] {/U0 }]/U0 ]]

# XDC: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/ip_0/jesd204_phy_1_gt_ooc.xdc

# XDC: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/synth/jesd204_phy_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_phy_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/synth/jesd204_phy_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_phy_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/synth/jesd204_phy_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_phy_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/jesd204_phy_1.xci
# IP: The module: 'jesd204_phy_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/ip_0/jesd204_phy_1_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_phy_1_gt || ORIG_REF_NAME==jesd204_phy_1_gt}]

# XDC: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/ip_0/jesd204_phy_1_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_phy_1_gt || ORIG_REF_NAME==jesd204_phy_1_gt}] {/U0 }]/U0 ]]

# XDC: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/ip_0/jesd204_phy_1_gt_ooc.xdc

# XDC: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/synth/jesd204_phy_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_phy_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/synth/jesd204_phy_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_phy_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/jesd204_phy_1/synth/jesd204_phy_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_phy_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
