webtalk_init -webtalk_dir C:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 13 22:10:08 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212432185_1777581404_210782497_401" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6b2388ad-d559-4e6b-b90b-00a3e8c350e2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f85dca42-c18d-48f6-8904-72a463e51b42" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3418 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_transmit -clientid 2004063092 -regid "212432185_1777581404_210782497_401" -xml C:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.hw/webtalk/usage_statistics_ext_labtool.xml -html C:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.hw/webtalk/usage_statistics_ext_labtool.html -wdm C:/Users/ryry0/Downloads/mu2e_UEM_firmware/mu2e_UEM_firmware.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
